---
- name: Playbook para instalar Docker em Ubuntu
  hosts: all
  become: yes

  tasks:
    #* Caso tenha executado e nao consiga atualizar os pacotes do sistema pois o bugou o sources.list
    # - name: Remover arquivo existente do repositório Docker (se necessário)
    #   ansible.builtin.file:
    #     path: /etc/apt/sources.list.d/docker.list
    #     state: absent

    - name: Atualizar pacotes do sistema
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar pacotes necessários
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present


    - name: Baixar chave GPG do Docker
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
        checksum: sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570
        mode: "0644"

    - name: Adicionar repositório Docker ao APT
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc]
          https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Atualizar cache de pacotes
      apt:
        update_cache: yes

    - name: Instalar Docker e seus componentes
      apt:
        name:
          - docker-ce
          - docker-compose
        state: present

    - name: Iniciar e habilitar o Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Adicionar usuário ao grupo Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Verificar a versão do Docker instalada
      shell: docker --version
      register: docker_version
      changed_when: false

    - name: Exibir versão do Docker
      debug:
        msg: "Versão do Docker: {{ docker_version.stdout }}"
