---
- name: Install Zabbix Agent 2
  hosts: all
  become: true

  tasks:
    # - name: Ensure required dependencies are installed
    #   ansible.builtin.apt:
    #     name:
    #       - libc6
    #       - libssl3t64
    #     state: present
        # update_cache: yes

    - name: Atualizar pacotes do sistema
      apt:
        update_cache: yes # Atualiza o cache de pacotes.
        # upgrade: dist   # Realiza uma atualização completa do sistema.
    - name: Download Zabbix repository package
      ansible.builtin.get_url:
        url: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu22.04_all.deb"
        dest: "/tmp/zabbix-release_latest.deb"

    - name: Install Zabbix repository package
      ansible.builtin.command:
        cmd: "dpkg -i /tmp/zabbix-release_latest.deb"
      # args:
      #   creates: "/etc/apt/sources.list.d/zabbix.list"

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Zabbix Agent 2 and plugins
      ansible.builtin.apt:
        name:
          - zabbix-agent2
          - zabbix-agent2-plugin-*
        state: present

    - name: Configure Zabbix Agent 2
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^Server=127.0.0.1'
        line: 'Server=10.24.125.2'
        state: present
        backup: yes

    - name: Restart Zabbix Agent 2 service
      ansible.builtin.service:
        name: zabbix-agent2
        state: restarted

    - name: Enable Zabbix Agent 2 service at boot
      ansible.builtin.service:
        name: zabbix-agent2
        enabled: yes
